#!/usr/bin/env bash
set -euo pipefail

# Error handling — fail open (exit 0) so we never block the agent
trap 'echo "[ConKeeper] post-tool-use.sh failed at line $LINENO" >&2; exit 0' ERR

# --- Dependencies ---

if ! command -v jq &>/dev/null; then
    exit 0
fi

# --- Parse hook input ---

input=$(cat)
tool_name=$(printf '%s' "$input" | jq -r '.tool_name // empty')
tool_input=$(printf '%s' "$input" | jq -r '.tool_input // empty')
session_id=$(printf '%s' "$input" | jq -r '.session_id // empty')
cwd=$(printf '%s' "$input" | jq -r '.cwd // empty')

# Validate session_id (security: prevents path traversal)
if [[ -z "$session_id" ]] || ! [[ "$session_id" =~ ^[a-zA-Z0-9_-]+$ ]]; then
    exit 0
fi

# Require memory directory to exist
[[ -d "${cwd:-.}/.claude/memory" ]] || exit 0

# --- Read configuration ---

observation_hook=true
observation_detail="full"

config_file="${cwd:-.}/.claude/memory/.memory-config.md"
if [[ -f "$config_file" ]]; then
    frontmatter=""
    in_frontmatter=false
    delimiter_count=0
    while IFS= read -r line; do
        if [[ "$line" == "---" ]]; then
            delimiter_count=$((delimiter_count + 1))
            if (( delimiter_count == 1 )); then
                in_frontmatter=true
                continue
            elif (( delimiter_count == 2 )); then
                break
            fi
        fi
        if [[ "$in_frontmatter" == true ]]; then
            line="${line%%#*}"
            frontmatter+="$line"$'\n'
        fi
    done < "$config_file"

    if [[ -n "$frontmatter" ]]; then
        parse_yaml_val() {
            local key="$1"
            local default="$2"
            local val
            val=$(printf '%s' "$frontmatter" | awk -F': *' -v k="$key" '$1 == k { gsub(/^[[:space:]]+|[[:space:]]+$/, "", $2); print $2 }')
            if [[ -n "$val" ]]; then
                printf '%s' "$val"
            else
                printf '%s' "$default"
            fi
        }
        observation_hook=$(parse_yaml_val "observation_hook" "$observation_hook")
        observation_detail=$(parse_yaml_val "observation_detail" "$observation_detail")
    fi
fi

# Check if observations are disabled
if [[ "$observation_hook" == "false" ]] || [[ "$observation_detail" == "off" ]]; then
    exit 0
fi

# --- Observation file path ---

obs_dir="${cwd:-.}/.claude/memory/sessions"
obs_file="$obs_dir/$(date +%Y-%m-%d)-observations.md"
mkdir -p "$obs_dir"

# Create file header if needed
if [[ ! -f "$obs_file" ]]; then
    printf '# Session Observations — %s\n<!-- Auto-generated by ConKeeper PostToolUse hook -->\n\n' "$(date +%Y-%m-%d)" > "$obs_file"
fi

# --- Classify tool and extract fields ---

timestamp=$(date +%H:%M:%S)

# Action type mapping (case statement for Bash 3.2 compat)
action=""
case "$tool_name" in
    Read|Glob|Grep)          action="read" ;;
    Write|Edit|MultiEdit|NotebookEdit) action="write" ;;
    Bash)                    action="execute" ;;
    WebFetch|WebSearch)      action="fetch" ;;
    Task)                    action="delegate" ;;
    *)                       action="other" ;;
esac

# Determine if this is a stub tool
is_stub=false
case "$tool_name" in
    Read|Write|Edit|Glob|Grep|MultiEdit|NotebookEdit)
        is_stub=true ;;
esac

# When observation_detail is stubs_only, all tools get stub entries
if [[ "$observation_detail" == "stubs_only" ]]; then
    is_stub=true
fi

# Extract file path from tool_input (truncate to 120 chars)
file_path=$(printf '%s' "$tool_input" | jq -r '.file_path // .path // .command // .pattern // "—"' 2>/dev/null | head -c 120) || file_path="—"

# --- Build and append entry ---

if [[ "$is_stub" == true ]]; then
    # Stub entry: timestamp | tool | action | path | — | success
    printf -- '- **%s** | `%s` | %s | `%s` | — | success\n' \
        "$timestamp" "$tool_name" "$action" "$file_path" >> "$obs_file"
else
    # Full entry: timestamp | tool | action | path | command_summary | success
    cmd_summary=$(printf '%s' "$tool_input" | jq -r '.command // "—"' 2>/dev/null | head -c 80) || cmd_summary="—"
    printf -- '- **%s** | `%s` | %s | `%s` | `%s` | success\n' \
        "$timestamp" "$tool_name" "$action" "$file_path" "$cmd_summary" >> "$obs_file"
fi

exit 0
